from __future__ import annotations

from pathlib import Path


DOCS = (
    Path("docs/current/qq-group-chatbot.md"),
    Path("docs/current/qq-group-chatbot-operations.md"),
)


def test_qq_group_chatbot_runbooks_cover_beta_operations() -> None:
    combined = "\n".join(path.read_text(encoding="utf-8") for path in DOCS)

    for required in (
        "Setup",
        "Config",
        "Run",
        "Pause",
        "Inspect",
        "Shutdown",
        "live-run",
        "init-beta",
        "beta-diagnostics",
        "diagnostics.sh",
        "operator-rehearsal.sh",
        "operator_rehearsal",
        "ISOTOPE_QQ_REHEARSAL_DATE",
        "first-run.sh",
        "first-run-rehearsal.sh",
        "beta-check",
        "startup-check",
        "ready",
        "profile_assets",
        "llm_reply_provider",
        "replay_report",
        "runtime.reply_provider",
        "reply_provider",
        "websocket_url",
        "next_steps",
        "review-dry-run",
        "beta-day-report",
        "beta-closeout",
        "beta-closeout.sh",
        "beta-closeout.json",
        "record-failure",
        "record-failure.sh",
        "close-failure",
        "close-failure.sh",
        "failure-to-regression.sh",
        "regression-intake",
        "dry-run-review.json",
        "beta-day-report.json",
        "regression-intake.json",
        "pytest_command",
        "can_enter_send_run",
        "pending_regression_drafts",
        "regressions/",
        "failures.json",
        "resolved_date",
        "ISOTOPE_QQ_CLOSE_FAILURE_DATE",
        "ready_for_send",
        "open_failure_count",
        "next_actions",
        "warnings",
        "init-profile",
        "apply-profile",
        "import-stickers",
        "manifest.json",
        "media_ref",
        "local_path",
        "required_sticker_ids",
        "missing_required_sticker_ids",
        "missing_local_paths",
        "use_frequency",
        "falls back to text",
        "`sticker_id` is not repeated",
        "sticker_candidate_block_reason_counts",
        "blocked_reasons",
        "use_frequency_zero",
        "recent_sticker_feedback",
        "no_matching_sticker",
        "init-replay",
        "init-replay-scenarios",
        "replay-scenarios",
        "replay-scenarios-report.json",
        "replay-scenario-reports",
        "--replay-scenarios-report",
        "replay_scenarios_report",
        "create_replay_scenarios",
        "run_replay_scenarios",
        "01-ship-it-candidate.json",
        "02-no-matching-sticker.json",
        "03-forbid-frequency-zero.json",
        "replay",
        "replay.json",
        "replay-report.json",
        "expectations",
        "passed",
        "min_sticker_candidates",
        "require_sticker_candidate_ids",
        "forbid_sticker_candidate_ids",
        "require_sticker_block_reasons",
        "forbid_sticker_block_reasons",
        "max_selected_sticker_actions",
        "sticker_candidate_ids",
        "selected_sticker_action_count",
        "require_all_dry_run",
        "role-card.json",
        "sticker-library.json",
        "send-run.sh",
        "ISOTOPE_QQ_ENABLE_SEND",
        "--send",
        "--max-events 0",
        "ISOTOPE_QQ_REAL_SMOKE",
        "qq_real_smoke.toml.example",
        "qq_real_smoke.local.toml",
        ".isotope/dev/qq-real-smoke.toml",
        "access_token",
        "ISOTOPE_QQ_REAL_SMOKE_MODE",
        "dry-run",
        "Automated real smoke must not send messages",
        "Role-Card Tuning",
        "Sticker Pack Setup",
        "Failure Log",
        "Multi-Day Checklist",
    ):
        assert required in combined
