"""Compatibility imports for the Supervisor dashboard command.

The dashboard implementation lives under ``isotope.features.supervisor.dashboard``;
this module keeps the existing command import path stable.
"""

from __future__ import annotations

from isotope.features.supervisor.dashboard.presentation import (
    active_terminal_match_text,
    best_linked_session_for_managed,
    best_linked_sessions_for_managed_lanes,
    candidate_snippet_matches,
    candidate_text_matches,
    candidate_thread_marker_matches,
    current_batch_payload,
    current_batch_payload_from_display_sessions,
    dashboard_active_goal_item,
    dashboard_current_payload,
    dashboard_display_sessions,
    dashboard_group_for,
    dashboard_item,
    dashboard_item_is_current,
    dashboard_item_suffix,
    dashboard_notification_counts,
    dashboard_notification_dict,
    dashboard_notification_source_ref,
    dashboard_payload,
    dashboard_state_snapshot,
    dashboard_state_snapshot_from_items,
    dashboard_state_snapshot_meta,
    dashboard_status_source,
    dependency_batch_items,
    dependency_blocked_text,
    dependency_item_name,
    empty_multi_worker_payload,
    handle_dashboard_command,
    is_current_managed_worker,
    is_generic_managed_prompt,
    is_generic_supervisor_status_prompt,
    is_missing_supervisor_worktree,
    linked_match_label,
    managed_link_analysis,
    managed_link_score,
    managed_prompt_matches_candidate,
    normalize_match_text,
    notification_dicts,
    print_dashboard_dependency_batch,
    print_dashboard_plain,
    text_contains,
    text_contains_positive,
)

__all__ = [
    "active_terminal_match_text",
    "best_linked_session_for_managed",
    "best_linked_sessions_for_managed_lanes",
    "candidate_snippet_matches",
    "candidate_text_matches",
    "candidate_thread_marker_matches",
    "current_batch_payload",
    "current_batch_payload_from_display_sessions",
    "dashboard_active_goal_item",
    "dashboard_current_payload",
    "dashboard_display_sessions",
    "dashboard_group_for",
    "dashboard_item",
    "dashboard_item_is_current",
    "dashboard_item_suffix",
    "dashboard_notification_counts",
    "dashboard_notification_dict",
    "dashboard_notification_source_ref",
    "dashboard_payload",
    "dashboard_state_snapshot",
    "dashboard_state_snapshot_from_items",
    "dashboard_state_snapshot_meta",
    "dashboard_status_source",
    "dependency_batch_items",
    "dependency_blocked_text",
    "dependency_item_name",
    "empty_multi_worker_payload",
    "handle_dashboard_command",
    "is_current_managed_worker",
    "is_generic_managed_prompt",
    "is_generic_supervisor_status_prompt",
    "is_missing_supervisor_worktree",
    "linked_match_label",
    "managed_link_analysis",
    "managed_link_score",
    "managed_prompt_matches_candidate",
    "normalize_match_text",
    "notification_dicts",
    "print_dashboard_dependency_batch",
    "print_dashboard_plain",
    "text_contains",
    "text_contains_positive",
]
