from isotope.runtime.in_process_workspace import InProcessWorkspaceMixin
from isotope.runtime.in_process_workspace_artifacts import InProcessArtifactMixin
from isotope.runtime.in_process_workspace_leases import InProcessWorkspaceLeaseMixin
from isotope.runtime.in_process_worker_handoff import InProcessWorkerHandoffMixin


def test_in_process_workspace_mixin_keeps_domain_boundaries():
    assert issubclass(InProcessWorkspaceMixin, InProcessArtifactMixin)
    assert issubclass(InProcessWorkspaceMixin, InProcessWorkspaceLeaseMixin)
    assert issubclass(InProcessWorkspaceMixin, InProcessWorkerHandoffMixin)
