import importlib

import pytest


REMOVED_PROXIES = (
    "isotope.action_compiler",
    "isotope.action_registry",
    "isotope.agent_runtime",
    "isotope.agent_loop_control",
    "isotope.agent_loop_planner_adapter",
    "isotope.agent_loop_step",
    "isotope.artifact_store",
    "isotope.assistant",
    "isotope.assistant.loop_control",
    "isotope.assistant.loop_planner_adapter",
    "isotope.assistant.loop_step",
    "isotope.assistant.real_planner_contract",
    "isotope.assistant.runtime",
    "isotope.capability_catalog",
    "isotope.capability_runner",
    "isotope.checkpoint_store",
    "isotope.codex_cli",
    "isotope.codex_live_smoke",
    "isotope.codex_server",
    "isotope.codex_task",
    "isotope.core.loop_control",
    "isotope.core.loop_planner_adapter",
    "isotope.core.loop_step",
    "isotope.core.real_planner_contract",
    "isotope.core.runtime",
    "isotope.executor",
    "isotope.event_schema",
    "isotope.event_store",
    "isotope.events",
    "isotope.errors",
    "isotope.execution.terminal_backend",
    "isotope.features.chat.product_chat",
    "isotope.features.supervisor.state.time_utils",
    "isotope.features.supervisor.state.worker_event_channel",
    "isotope.http_api",
    "isotope.ids",
    "isotope.ingestion",
    "isotope.integrations.llm",
    "isotope.integrations.llm.provider",
    "isotope.integrations.llm.tool_bridge",
    "isotope.llm_product_chat_app",
    "isotope.llm_provider",
    "isotope.model_tool_bridge",
    "isotope.models",
    "isotope.platform.schemas.models",
    "isotope.projector",
    "isotope.real_planner_adapter_contract",
    "isotope.refs",
    "isotope.retrieval",
    "isotope.runtime.server",
    "isotope.server",
    "isotope.terminal",
    "isotope.terminal_backend",
    "isotope.terminal_system_runner",
    "isotope.tool_protocol",
    "isotope.tools",
    "isotope.tools.write_artifact",
)


@pytest.mark.parametrize("module_path", REMOVED_PROXIES)
def test_removed_compat_proxies_are_not_importable(module_path):
    with pytest.raises(ModuleNotFoundError):
        importlib.import_module(module_path)
